name: cost-monitor-ci

on:
  push:
    branches:
      - main
      - general
  pull_request:

env:  
  AWS_REGION : "us-east-1"
  ROLE_TO_ASSUME: ${{ github.ref_name == 'main' && 'arn:aws:iam::873580382677:role/GitHubAction-AssumeRoleWithAction' || 'arn:aws:iam::016714367715:role/GitHubAction-AssumeRoleWithAction' }}

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read

jobs:
  cost-monitor:
    runs-on: ubuntu-latest  
    environment: ${{ github.ref_name == 'main' && 'production' || 'general' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Terraform Init General
        working-directory: ./terraform/
        if: github.ref_name == 'general'
        run: terraform init -backend-config=backend-general.hcl

      - name: Terraform Init Production
        working-directory: ./terraform/
        if: github.ref_name == 'main'
        run: terraform init -backend-config=backend-production.tf

      - name: Terraform Validate
        working-directory: ./terraform/
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform/
        run: terraform plan